En este capítulo, vamos a sumergirnos en el mundo del béisbol. En el camino, nos familiarizaremos con los conceptos básicos de numpy, un poderoso paquete para ciencia de datos.

Ya se ha definido una lista ```baseball``` en el script de Python, que representa la altura de algunos jugadores de béisbol en centímetros. ¿Puedes agregar algún código aquí y allá para crear un vector numpy a partir de él?

In [2]:
# Importa el paquete numpy como np
import numpy as np

# Crea la lista baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Crea un vector numpy con baseball: np_baseball
np_baseball = np.array(baseball) 

# Imprime el tipo de np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


## Altura de los beisbolistas
Eres un gran fanático del béisbol. Decides llamar a la MLB (Major League Baseball) y pedir más estadísticas sobre la altura de los jugadores principales. Te pasan datos sobre más de mil jugadores, que se almacenan como una lista de Python: ```height_in```. La altura se expresa en pulgadas. ¿Puedes convertirla en un vector ```numpy``` y convertir las unidades a metros?

```height_in``` ya está disponible y el paquete ```numpy``` está cargado, por lo que puedes comenzar de inmediato (Fuente: stat.ucla.edu).

height_in es una BD x por lo que no funcionará el codigo siguiente

In [3]:
# Importa numpy
import numpy as np

# Crea un vector numpy desde height_in: np_height_in
np_height_in = np.array(height_in)

# Imprime np_height_in
print(np_height_in)

# Convierte np_height_in a metros: np_height_m
np_height_m = np_height_in * 0.0254

# Imprime np_height_m
print(np_height_m)

NameError: name 'height_in' is not defined

La MLB también te permitirá analizar los datos de peso de los jugadores de béisbol. Una vez más, ambos están disponibles como listas de Python: ```height_in``` y ```weight_lb```. ```height_in``` está en pulgadas y ```weight_lb``` está en libras.

Ahora es posible calcular el IMC de cada jugador de béisbol. El código de Python para convertir ```height_in``` en un vector numpy con las unidades correctas ya está disponible en el espacio de trabajo. ¡Sigue las instrucciones paso a paso y termina el juego! ```height_in``` y ```weight_lb``` están disponibles como listas.

In [ ]:
# Importa numpy
import numpy as np

# Crea un vector desde height_in con unidades métricas: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Crea un vector a partir de weight_lb con unidades métricas: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calcular el IMC: bmi
bmi = np_weight_kg / np_height_m ** 2

# Imprime bmi
print(bmi)

## Beisbolistas peso ligero
Para crear subconjuntos tanto de listas regulares de Python como de matrices y vectores ```numpy```, puedes usar corchetes:
```python
x = [4 , 9 , 6, 3, 1]
x[1]
import numpy as np
y = np.array(x)
y[1]
```
Para ```numpy``` específicamente, también puedes usar matrices booleanas ```numpy```:
```python
high = y > 5
y[high]
```
Ya se incluye el código que calcula el IMC de todos los beisbolistas. ¡Sigue las instrucciones y revela cosas interesantes de los datos! ```height_in``` y ```weight_lb``` están disponibles como listas regulares.

In [ ]:
# Importa numpy
import numpy as np

# Calcular el IMC: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Crea el vector light
light = np.array(bmi < 21)

# Imprime light
print(light)

# Imprime los IMC de todos los jugadores de béisbol cuyo IMC sea inferior a 21
print(bmi[light])

## Efectos secundarios de NumPy
Como Hugo explicó previamente, ```numpy``` es excelente para hacer aritmética vectorial. Sin embargo, si comparas su funcionalidad con las listas regulares de Python, algunas cosas han cambiado.

En primer lugar, las matrices ```numpy``` no pueden contener elementos con diferentes tipos. Si intentas construir una lista de este tipo, algunos de los tipos de elementos se cambian para tener una lista homogénea. Esto se conoce como ```coerción de tipo```.

En segundo lugar, los operadores aritméticos típicos, como $+$, $-$, $*$ y $/$ tienen un significado diferente para las listas regulares de Python y las matrices y vectores ```numpy```.

Echa un vistazo a esta línea de código:
```python
np.array([True, 1, 2]) + np.array([3, 4, False])
```
¿Puedes seleccionar el fragmento de código que crea exactamente el mismo objeto en Python?

R/ ```np.array([4, 3, 0]) + np.array([0, 2, 2])```


Se suman elemento por elemento, no se concatenan como en las listas normales de python

In [4]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [5]:
np.array([4, 3, 0]) + np.array([0, 2, 2])

array([4, 5, 2])

## Subdivisión de vectores NumPy
Lo has visto con tus propios ojos: Las listas de Python y las matrices ```numpy``` a veces se comportan de manera diferente. Por suerte, todavía hay certezas en este mundo. Por ejemplo, la creación de subconjuntos (usando la notación de corchetes en listas o matrices y vectores) funciona exactamente igual. Para ver esto por ti mismo, prueba las siguientes líneas de código en el IPython Shell:
```python
x = ["a", "b", "c"]
x[1]

np_x = np.array(x)
np_x[1]
```
El script en el editor ya contiene código que importa ```numpy``` como ```np``` y almacena tanto la altura como el peso de los jugadores de la MLB como vectores ```numpy```. ```height_in``` y ```weight_lb``` están disponibles como listas regulares.

In [ ]:
# Importa numpy
import numpy as np

# Almacena las listas weight y height como vectores numpy
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Imprime el índice 50 de np_weight_lb
print(np_weight_lb[50])

# Imprime el sub vector de np_height_in: desde el índice 100 hasta el índice 110 incluidos
print(np_height_in[100:111])

## Tu primer matriz 2D en NumPy
Antes de trabajar con los datos reales de MLB, intentemos crear una matriz ```numpy``` 2D a partir de una pequeña lista de listas.

En este ejercicio, ```baseball``` es una lista de listas. La lista principal contiene 4 elementos. Cada uno de estos elementos es una lista que contiene la altura y el peso de 4 jugadores de béisbol, en ese orden. ```baseball``` ya está codificado para ti en el guión.

In [7]:
# Importa numpy
import numpy as np

# Crea baseball, una lista de listas
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Crea una matriz numpy 2D de baseball: np_baseball
np_baseball = np.array(baseball)
print(np_baseball)

# Imprime el tipo de np_baseball
print(type(np_baseball))

# Imprime el atributo shape de np_baseball
print(np_baseball.shape)

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
<class 'numpy.ndarray'>
(4, 2)


## Datos de béisbol en formato 2D
Echa otro vistazo a los datos de MLB y te darás cuenta de que tiene más sentido reestructurar toda esta información en una matriz ```numpy``` 2D. Esta matriz debe tener 1015 filas, correspondientes a los 1015 jugadores de béisbol sobre los que se tiene información, y 2 columnas (para altura y peso).

La MLB fue, nuevamente, muy útil y te pasó los datos en una estructura diferente, una lista de listas de Python. En esta lista de listas, cada sublista representa la altura y el peso de un solo jugador de béisbol. El nombre de esta lista de listas es ```baseball```.

¿Puedes almacenar los datos como una matriz 2D para aprovechar la funcionalidad adicional de ```numpy```? ```baseball``` está disponible como una lista de listas regular.

In [ ]:
# Importa el paquete numpy
import numpy as np

# Crea una matriz numpy 2D de baseball: np_baseball
np_baseball = np.array(baseball)

# Imprime el atributo shape de np_baseball
print(np_baseball.shape)

## Subdivisión de matrices NumPy 2D
Si tu matriz ```numpy``` 2D tiene una estructura regular, es decir, cada fila y columna tiene un número fijo de valores, subdividir se vuelve muy fácil. Echa un vistazo al código a continuación donde los elementos "a" y "c" se extraen de una lista de listas.
```python
# lista de listas regular
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:, 0]
```
Para las listas regulares de Python, esto es un verdadero dolor de cabeza. Sin embargo, para las matrices ```numpy``` 2D, ¡es bastante intuitivo! Los índices antes de la coma se refieren a las filas, mientras que los que están después de la coma se refieren a las columnas. El ```:``` es para rebanar; en este ejemplo, le dice a Python que incluya todas las filas.

El código que convierte la lista ```baseball``` precargada en una matriz ```numpy``` 2D ya está en el script. La primera columna contiene la altura de los jugadores en pulgadas y la segunda columna contiene el peso de los jugadores en libras. Agrega algunas líneas para hacer las selecciones correctas. ¡Recuerda que en Python, el primer elemento está en el índice 0! ```baseball``` está disponible como una lista de listas regular.

In [ ]:
# Importa el paquete numpy
import numpy as np

# Crea np_baseball (2 columnas)
np_baseball = np.array(baseball)

# Imprime la fila 50 de np_baseball
print(np_baseball[49])

# Selecciona toda la segunda columna de np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Imprime la altura del jugador 124
print(np_baseball[123,0])

## Aritmética 2D
¿Recuerdas cómo calculaste el índice de masa corporal para todos los jugadores de béisbol? ```numpy``` pudo realizar todos los cálculos al nivel elemento (es decir, elemento por elemento). ¡Para matrices ```numpy``` 2D no es diferente! Puedes combinar matrices con números, con vectores y con otras matrices.

Ejecuta el siguiente código en el shell de IPython y ve si queda claro:
```python
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat
```
```np_baseball``` está codificado para ti; es nuevamente una matriz ```numpy``` 2D con 3 columnas que representan la altura (en pulgadas), el peso (en libras) y la edad (en años). ```baseball``` está disponible como una lista de listas regular y ```updated``` está disponible como matriz ```numpy``` 2D.

In [ ]:
# Importa el paquete numpy
import numpy as np

# Crea np_baseball (3 columnas)
np_baseball = np.array(baseball)

# Imprime la suma de np_baseball y updated
print(np_baseball + updated)

# Crea una matriz numpy: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Imprime el producto de np_baseball y conversion
print(np_baseball * conversion)

## Promedio versus mediana
Ahora sabes cómo usar funciones ```numpy``` para tener una mejor visión de tus datos. Básicamente se trata de importar ```numpy``` y luego llamar a varias funciones simples en las matrices ```numpy```:
```python
import numpy as np
x = [1, 4, 8, 10, 12]
np.mean(x)
np.median(x)
```
Los datos de béisbol están disponibles como una matriz ```numpy``` 2D con 3 columnas (altura, peso, edad) y 1015 filas. El nombre de esta matriz ```numpy``` es ```np_baseball```. Sin embargo, después de reestructurar los datos, observas que algunos valores de altura son anormalmente altos. Sigue las instrucciones y descubre qué estadística de resumen es la más adecuada si se trata de los denominados valores atípicos. ```np_baseball``` está disponible.

In [8]:
# Importa numpy
import numpy as np

# Crea np_height_in usando np_baseball
np_height_in = np.array(np_baseball[:, 0])

# Imprime la media de np_height_in
print(np.mean(np_height_in))

# Imprime la mediana de np_height_in
print(np.median(np_height_in))

198.25
199.0


## Explora los datos de béisbol
Debido a que la media y la mediana están tan alejadas, decides presentar una queja ante la MLB. Encuentran el error y te envían los datos corregidos. Están nuevamente disponibles como una matriz 2D ```NumPy np_baseball```, con tres columnas.

El script de Python en el editor ya incluye código para imprimir mensajes informativos con las diferentes estadísticas de resumen. ¿Puedes terminar el trabajo? ```np_baseball``` está disponible.

In [10]:
# Importa numpy
import numpy as np

# Imprime la altura media (primera columna)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Imprime altura mediana. Reemplaza 'None'
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

# Imprime la desviación estándar de la altura. Reemplaza 'None'
stddev = np.std(np_baseball[:, 0])
print("Standard Deviation: " + str(stddev))

# Imprime la correlación entre la primera y la segunda columnas. Reemplaza 'None'
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


## Juntemos todo
En los últimos ejercicios hemos visto todo lo que hay que saber sobre la altura y el peso de los jugadores de béisbol. Ahora es el momento de sumergirse en otro deporte: el fútbol.

Te has puesto en contacto con la FIFA y te han pasado dos listas. Las listas son las siguientes:
```python
positions = ['GK', 'M', 'A', 'D', ...]
heights = [191, 184, 185, 180, ...]
```
Cada elemento de las listas corresponde a un jugador. La primera lista, ```positions```, contiene cadenas que representan la posición de cada jugador. Las posiciones son: ```'GK (portero)```, ```'M' (medio)```, ```'A' (delantero)``` y ```'D' (defensa)```. La segunda lista, ```heights```, contiene números enteros que representan la altura del jugador en cm. El primer jugador de las listas es portero y es bastante alto (191 cm).

Estás bastante seguro de que la altura media de los porteros es más alta que la de otros jugadores en el campo de fútbol. Algunos de tus amigos no te creen, por lo que estás decidido a mostrárselos usando los datos que recibiste de FIFA y tus habilidades de Python recién adquiridas. ```heights``` y ```positions``` están disponibles como listas.

In [ ]:
# Import numpy
import numpy as np

# Convierte positions y heights en matrices numpy: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Alturas de los porteros: gk_heights
gk_heights = np_heights[np_positions == "GK"]

# Alturas de los otros jugadores: other_heights
other_heights = np_heights[np_positions != "GK"]

# Imprime la altura mediana de los porteros. Reemplaza 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Imprime la altura mediana de los otros jugadores. Reemplaza 'None'
print("Median height of other players: " + str(np.median(other_heights)))